// <auto-generated />
using System;
using MegaStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaStore.Web.Migrations
{
    [DbContext(typeof(MegaStoreDbContext))]
    [Migration("20240529190134_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        
    }
}
